server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    # 日期格式化

    date-format: yyyy-MM-dd HH:mm:ss

    # 序列化相关
    serialization:
      # 格式化输出
      indent_output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: true
    # 反序列化相关
    deserialization:
      # 解析json时，遇到不存在的属性就忽略
      fail_on_unknown_properties: false
    # 设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    parser:
      # 允许特殊和转义符
      allow_unquoted_control_chars: true
      # 允许单引号
      allow_single_quotes: true
  redis:
    timeout: 3000
    lettuce:
      pool:
        min-idle: 1
        max-active: 8
        max-idle: 8
    # 哨兵集群
#    sentinel:
#      master: master
#      nodes: 192.168.62.100:26379,192.168.62.100:26380,192.168.62.100:26381
    # 单机版本
    port: 6379
    host: 192.168.62.100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  auto-dialect: true
logging:
  file:
    path: log
